In [3]:
import json

file_path = "cached_article_database.jsonl"

# Read and store JSONL data
articles = []
with open(file_path, "r", encoding="utf-8") as file:
    for i, line in enumerate(file):
        data = json.loads(line)
        articles.append(data)
        print(f"Line {i+1}: {data}")

        # Preview only first 5 lines
        if i == 4:
            break

Line 1: {'title': 'Mitsubishi Chemical expands production capacities', 'paragraphs': {'p1': 'Tokyo-based Mitsubishi Chemical wants to boost up its battery electrolyte business. It plans several strategic steps due to growing demand on the electric vehicle market.', 'p2': 'The company plans to restarting production in a factory based in Britain and doubling its output in the States. Part of the reconstruction plan is also to close a factory in China. The company is said to be even willing to temporarily limit its mobile device battery production.', 'p3': 'Initially, the UK plant has built batteries since 2012. However, the anticipated demand did not arise, so the production lines were stopped in March 2016.asia.nikkei.com', 'p4': 'Your email address will not be published.Required fields are marked*', 'p5': 'Name *', 'p6': 'E-Mail *', 'p7': 'I agree with thePrivacy policy', 'p8': "We have been covering the development of electric mobility with journalistic passion and expertise since 2011. As the industry's leading specialist media, we offer comprehensive reporting of the highest quality - as a central platform for the rapid ramp-up of this technology. With news, background information, driving reports, interviews, videos as well as advertising messages.", 'p9': '© 2024 electrive.com'}, 'meta': {'ID': '1100001', 'date': '04-12-2017', 'url': 'https://www.electrive.com/2017/12/04/mitsubishi-chemical-expands-capacities-due-high-demand/'}}
Line 2: {'title': 'BYD tackles renewables – new battery strategy', 'paragraphs': {'p1': 'The Chinese EV maker BYD wants to increase its foothold in the market for renewable energy. The strategy includes advances in batteries such as the reduction of the use of rare earths as well as 2nd life scenarios.', 'p2': 'In its latest press release BYD has become a self-described “renewable energy company” not unlike Tesla. For BYD this means they are to gradually increase the production of electric vehicle and energy storage batteries and reduce the proportion of rare earth material in the batteries. The plan was unveiled at Battery Japan 2018 as part of Tokyo‘s World Smart Energy Week. BYD also released a new solar module there.', 'p3': 'Furthermore, BYD said it has begun to reuse batteries removed from decommissioned electric vehicles, recycling some for communication use in base stations, energy storage power stations, as well as other types of facilities and equipment. Batteries that cannot be re-used are disassembled.', 'p4': 'Such battery recycling and 2nd life uses are required in China nowadays. The government in Beijingreportedlypublished new rules that hold makers of electric vehicles responsible to collect and recycle their batteries.', 'p5': 'UPDATE March, 21: BYD appears quick to act upon Beijing’s call for recycling.Reutersreports BYD plans to open a battery recycling facility in Shanghai no later than in the upcoming Q2. While the plant is said to stand already, no details have been made public.', 'p6': 'electrive.com(PI),reuters.com'}, 'meta': {'ID': '1100006', 'date': '05-03-2018', 'url': 'https://www.electrive.com/2018/03/05/byd-tackles-renewable-energy-sector-battery-strategy/'}}
Line 3: {'title': 'BASF and Toda found cathode subsidiary in USA', 'paragraphs': {'p1': 'The announced founding of a new subsidiary company by BASF and Toda has now been completed. BASF Toda America (BTA) will be making NCM and NCA cathode materials for use in e-mobility. The move is part of BASF’s globalisation strategy.', 'p2': 'BASF and Todayannouncedin December that they would be adapting their structures to focus more on expanding their business in the USA, and would be bundling their factories in Elyria, Ohio and Battle Creek, Michigan, under the terms of a joint venture.', 'p3': 'The founding of this joint venture marks the second time BASF and Toda are cooperating. The already existing BASF Toda Battery Materials has been preparing to ramp up production capabilities and securing a supply of cathode materials to address the growing e-mobility market in North America.\xa0The German company is hoping to work better with the U.S. market with a local production facility and more direct access to consumers.', 'p4': 'BASF is looking to set up local production globally though. The most recent production expansion was\xa0 in the Japanese manufacturing plant in Onoda, which produces cathode materials with a high nickel percentage. Capacities there tripled, and the largest calcination plant has taken up operation there.', 'p5': 'The President of BASF’s Catalysts Division, Kenneth Lane said: “With this investment, BASF is executing its vision to establish a global manufacturing presence for battery materials and responding to growing market needs.”', 'p6': 'In Europe, BASFannounced already last yearto invest 400m euros to build production plants for cathode materials. The material for those parts will come from Russia and Finland however, where BASF has signed an MoU with Norilsk Nickel (Nornickel) to provide nickel and cobalt.', 'p7': 'BASF is currently supplying components for the major vehicle platforms, and is in the qualifying process for emerging technologies that will replace the current models. One example is its recentcooperation with Sion Poweras they seek to develop Li-metal batteries.', 'p8': 'basf.com'}, 'meta': {'ID': '1100009', 'date': '10-03-2018', 'url': 'https://www.electrive.com/2018/03/10/basf-and-toda-found-battery-subsidiary/'}}
Line 4: {'title': 'Forsee Power to boost up battery production capacity', 'paragraphs': {'p1': 'The French battery specialist raises 55m euros to increase its production capacity tenfold. With this move, the company seeks to step up serial production of battery systems for buses, trucks, vessels and scooters in Europe as well as China.', 'p2': 'The fresh money comes from Mitsui and the European Investment Bank, among others. In early 2016, Forsee Power opened a new facility in Greater Paris.forseepower.com'}, 'meta': {'ID': '1100010', 'date': '02-01-2018', 'url': 'https://www.electrive.com/2018/01/02/forsee-power-boost-battery-production-capacity/'}}
Line 5: {'title': 'Northvolt secures support from European Investment Bank', 'paragraphs': {'p1': 'Northvolt has secured financing of up 52,5 million euros from the European Investment Bank, based in Luxembourg, in order to construct a demonstration of its planned battery cell factory in Sweden.', 'p2': 'Theyrecently also received fundingfrom the Swedish Energy Agency valued around 15 million euros. The pilot line will be developed alongside a research lab under the Northvolt Labs banner. The centre will serve to qualify and industrialise products and processes together with partners and customers.', 'p3': 'The location of the planned facility will be in Swedish Västerås. According to a statement by the company, Northvolt Labs is an important step to the realisation of the planned lithium-ion battery factory in Skellefteå, which they hope will reach an annual production volume of 32 GWh. They plan to produce batteries for transportation and energy storage and to employ around 300 to 400 people.', 'p4': 'The construction of the pilot line, which is directly funded by the subsidies, is set to begin in the coming months. Peter Carlsson, formerly a Tesla manager, and now CEO of Northvolt, thinks that the financial boost will help them realise their plan to eventually build the “greenest battery in the world”, as well as a strong and competitive supply chain model for battery production in Europe.', 'p5': 'These are also the kind of developments that EU Energy Commissioner Maroš Šefčovič had in mind when herecently spokeof a European partnership to grow a local battery industry, and address the potential battery shortage that is emerging as demand for batteries is skyrocketing, and production is simply not keeping up.', 'p6': 'Recently Northvolt brought utility vehicle producer Scania on board, and the two companies plan to develop batteries in cooperation for the use in heavy industrial vehicles. Scania invested 10 million euros into the venture, whereas some of the money will also be used to fund the research lab.', 'p7': 'reuters.com,euractiv.com,northvolt.com'}, 'meta': {'ID': '1100013', 'date': '13-02-2018', 'url': 'https://www.electrive.com/2018/02/13/northvolt-secures-support-european-investment-bank/'}}

In [4]:
import pandas as pd
from IPython.display import display

# Convert to Pandas DataFrame for better visualization
df = pd.DataFrame(articles)

# Display in notebook
display(df)

,title,paragraphs,meta
0,Mitsubishi Chemical expands production capacities,{'p1': 'Tokyo-based Mitsubishi Chemical wants ...,"{'ID': '1100001', 'date': '04-12-2017', 'url':..."
1,BYD tackles renewables – new battery strategy,{'p1': 'The Chinese EV maker BYD wants to incr...,"{'ID': '1100006', 'date': '05-03-2018', 'url':..."
2,BASF and Toda found cathode subsidiary in USA,{'p1': 'The announced founding of a new subsid...,"{'ID': '1100009', 'date': '10-03-2018', 'url':..."
3,Forsee Power to boost up battery production ca...,{'p1': 'The French battery specialist raises 5...,"{'ID': '1100010', 'date': '02-01-2018', 'url':..."
4,Northvolt secures support from European Invest...,{'p1': 'Northvolt has secured financing of up ...,"{'ID': '1100013', 'date': '13-02-2018', 'url':..."

In [12]:
processed_articles = []
for raw_data in articles:
    paragraphs = [raw_data[key] for key in sorted(raw_data.keys()) if key.startswith("p")]

        #ectract the meta-data object
    meta_data = raw_data.get("meta", {})

    # Transform data to fit the new schema
    article = {
        "title": raw_data.get("title", ""),
        "paragraphs": paragraphs,  # Store paragraphs as a list
        "meta": {
            "ID": meta_data.get("ID", ""),
            "date": meta_data.get("date", ""),
            "url": meta_data.get("url", "")
        }
    }

    processed_articles.append(article)

# Display sample processed articles
display(pd.DataFrame(processed_articles).head())

,title,paragraphs,meta
0,Mitsubishi Chemical expands production capacities,[{'p1': 'Tokyo-based Mitsubishi Chemical wants...,"{'ID': '1100001', 'date': '04-12-2017', 'url':..."
1,BYD tackles renewables – new battery strategy,[{'p1': 'The Chinese EV maker BYD wants to inc...,"{'ID': '1100006', 'date': '05-03-2018', 'url':..."
2,BASF and Toda found cathode subsidiary in USA,[{'p1': 'The announced founding of a new subsi...,"{'ID': '1100009', 'date': '10-03-2018', 'url':..."
3,Forsee Power to boost up battery production ca...,[{'p1': 'The French battery specialist raises ...,"{'ID': '1100010', 'date': '02-01-2018', 'url':..."
4,Northvolt secures support from European Invest...,[{'p1': 'Northvolt has secured financing of up...,"{'ID': '1100013', 'date': '13-02-2018', 'url':..."

In [13]:
if processed_articles:
    print(json.dumps(processed_articles[0], indent=4))

{
    "title": "Mitsubishi Chemical expands production capacities",
    "paragraphs": [
        {
            "p1": "Tokyo-based Mitsubishi Chemical wants to boost up its battery electrolyte business. It plans several strategic steps due to growing demand on the electric vehicle market.",
            "p2": "The company plans to restarting production in a factory based in Britain and doubling its output in the States. Part of the reconstruction plan is also to close a factory in China. The company is said to be even willing to temporarily limit its mobile device battery production.",
            "p3": "Initially, the UK plant has built batteries since 2012. However, the anticipated demand did not arise, so the production lines were stopped in March 2016.asia.nikkei.com",
            "p4": "Your email address will not be published.Required fields are marked*",
            "p5": "Name *",
            "p6": "E-Mail *",
            "p7": "I agree with thePrivacy policy",
            "p8": "We have been covering the development of electric mobility with journalistic passion and expertise since 2011. As the industry's leading specialist media, we offer comprehensive reporting of the highest quality - as a central platform for the rapid ramp-up of this technology. With news, background information, driving reports, interviews, videos as well as advertising messages.",
            "p9": "\u00a9 2024 electrive.com"
        }
    ],
    "meta": {
        "ID": "1100001",
        "date": "04-12-2017",
        "url": "https://www.electrive.com/2017/12/04/mitsubishi-chemical-expands-capacities-due-high-demand/"
    }
}

In [17]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
uri = "mongodb+srv://mainamathengej:296ygHRG7TRnmCaW@tuone-cluster.7mato.mongodb.net/?retryWrites=true&w=majority&appName=tuone-cluster"
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))
# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

tuone-cluster-shard-00-01.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),tuone-cluster-shard-00-00.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),tuone-cluster-shard-00-02.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67ae51e3c649b7e5a2f53529, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('tuone-cluster-shard-00-00.7mato.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('tuone-cluster-shard-00-00.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('tuone-cluster-shard-00-01.7mato.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('tuone-cluster-shard-00-01.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('tuone-cluster-shard-00-02.7mato.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('tuone-cluster-shard-00-02.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

In [18]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
uri = "mongodb+srv://mainamathengej:296ygHRG7TRnmCaW@tuone-cluster.7mato.mongodb.net/?retryWrites=true&w=majority&appName=tuone-cluster"
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))
# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

tuone-cluster-shard-00-01.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),tuone-cluster-shard-00-02.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),tuone-cluster-shard-00-00.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67ae525dc649b7e5a2f5352a, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('tuone-cluster-shard-00-00.7mato.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('tuone-cluster-shard-00-00.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('tuone-cluster-shard-00-01.7mato.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('tuone-cluster-shard-00-01.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('tuone-cluster-shard-00-02.7mato.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('tuone-cluster-shard-00-02.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

In [21]:
import pymongo

uri = "mongodb+srv://mainamathengej:296ygHRG7TRnmCaW@tuone-cluster.7mato.mongodb.net/?retryWrites=true&w=majority"

try:
    client = pymongo.MongoClient(uri, server_api=pymongo.server_api.ServerApi('1'))
    client.admin.command('ping')
    print("✅ Successfully connected to MongoDB!")
except Exception as e:
    print("❌ Connection failed:", e)

❌ Connection failed: tuone-cluster-shard-00-00.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),tuone-cluster-shard-00-02.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),tuone-cluster-shard-00-01.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 67ae55a5c649b7e5a2f5352d, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('tuone-cluster-shard-00-00.7mato.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('tuone-cluster-shard-00-00.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('tuone-cluster-shard-00-01.7mato.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('tuone-cluster-shard-00-01.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('tuone-cluster-shard-00-02.7mato.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('tuone-cluster-shard-00-02.7mato.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

In [ ]:
import os
from pymongo import MongoClient
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Get MongoDB credentials from environment variables
MONGO_URI = os.getenv("MONGO_URI")
DB_NAME = os.getenv("MONGO_DB_NAME")
COLLECTION_NAME = os.getenv("MONGO_COLLECTION_NAME")

# Connect to MongoDB
client = MongoClient(MONGO_URI)
db = client[DB_NAME]
collection = db[COLLECTION_NAME]